import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header } from "@/components/Header";
import { Navigation } from "@/components/Navigation";
import ApearanceProvider from "@/app/context/Themecontext";
import { ApearanceContext } from "@/app/context/Themecontext";
import { useContext } from "react";
import NavigationLayout from './layouts/NavigationLayout';
import { AnimatePresence } from "framer-motion";

import PageWrapper from "@/components/wrapper/PageWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // window.scrollTo(0, 0)
  console.log('RootLayout')
  return (
    <html lang="en">
      <ApearanceProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased   `}
        >
          <NavigationLayout>
            <PageWrapper>
              {children}
            </PageWrapper>
          </NavigationLayout>
        </body>
      </ApearanceProvider>
    </html>
  );
}
